# Generated by Django 5.1.3 on 2024-11-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletime',
            name='end_date',
            field=models.DateField(default='2024-12-6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycletime',
            name='start_date',
            field=models.DateField(default='2024-12-1'),
            preserve_default=False,
        ),
    ]
