# Generated by Django 5.1.3 on 2024-11-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cycletime_end_date_cycletime_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CycleTime',
            new_name='Task',
        ),
    ]
